// Vedic Nakshatra (birth star) reference content.
//
// This is deliberately a static, educational reference — not a calculator. Determining a
// person's actual birth Nakshatra requires the Moon's precise sidereal longitude at the exact
// moment of birth, which in turn requires real ephemeris data and an accurate birth time. That
// is explicitly out of scope for this app (same reason moon sign / rising sign / houses are out
// of scope): we do not want to show users a computed answer that could easily be wrong. Instead,
// people can browse all 27 traditional Nakshatras here, or manually select their own if they
// already know it from a Vedic birth chart or a priest/astrologer.

export interface NakshatraInfo {
  slug: string;
  name: string;
  order: number; // 1-27
  deity: string;
  rulingPlanet: string;
  symbol: string;
  description: string;
}

export const NAKSHATRAS: NakshatraInfo[] = [
  { slug: "ashwini", name: "Ashwini", order: 1, deity: "The Ashwini Kumaras (twin divine healers)", rulingPlanet: "Ketu", symbol: "Horse's head", description: "Ashwini is traditionally associated with speed, healing, and new beginnings — the first Nakshatra, said to carry the energy of a fresh start. Those connected to it are often described as quick-acting, curious, and drawn to helping others heal." },
  { slug: "bharani", name: "Bharani", order: 2, deity: "Yama, god of death and dharma", rulingPlanet: "Venus", symbol: "Yoni (womb)", description: "Bharani carries themes of transformation, restraint, and the full cycle of life and death in Vedic tradition. It is traditionally linked to strong willpower, deep passion, and the discipline needed to carry heavy responsibility." },
  { slug: "krittika", name: "Krittika", order: 3, deity: "Agni, god of fire", rulingPlanet: "Sun", symbol: "Razor or flame", description: "Krittika is traditionally associated with sharp discernment and purifying fire — cutting away what doesn't serve growth. Those connected to it are often described as determined, direct, and unafraid of confrontation when principle is at stake." },
  { slug: "rohini", name: "Rohini", order: 4, deity: "Brahma / Prajapati", rulingPlanet: "Moon", symbol: "Cart or chariot, ox cart", description: "Rohini is considered one of the most auspicious Nakshatras, traditionally linked to beauty, fertility, and material growth. It is associated with charm, creativity, and a magnetic, nurturing presence." },
  { slug: "mrigashira", name: "Mrigashira", order: 5, deity: "Soma, the Moon god", rulingPlanet: "Mars", symbol: "Deer's head", description: "Mrigashira means 'deer's head' and traditionally represents gentle searching and curiosity. Those connected to it are often described as soft-spoken seekers, always looking for something just out of reach." },
  { slug: "ardra", name: "Ardra", order: 6, deity: "Rudra, storm deity", rulingPlanet: "Rahu", symbol: "Teardrop or diamond", description: "Ardra is associated with storms, upheaval, and the intense transformation that follows destruction. In tradition it represents the emotional intensity required to clear away the old to make room for renewal." },
  { slug: "punarvasu", name: "Punarvasu", order: 7, deity: "Aditi, mother goddess of boundlessness", rulingPlanet: "Jupiter", symbol: "Bow and quiver", description: "Punarvasu means 'return of the light' and is traditionally tied to renewal, optimism, and safe return after hardship. It is associated with resilience, generosity, and a nurturing, expansive spirit." },
  { slug: "pushya", name: "Pushya", order: 8, deity: "Brihaspati, guru of the gods", rulingPlanet: "Saturn", symbol: "Lotus or cow's udder", description: "Pushya is widely considered one of the most auspicious Nakshatras in Vedic tradition, associated with nourishment, spiritual growth, and protective care. Those connected to it are often described as dutiful, wise, and instinctively supportive of others." },
  { slug: "ashlesha", name: "Ashlesha", order: 9, deity: "The Nagas, serpent deities", rulingPlanet: "Mercury", symbol: "Coiled serpent", description: "Ashlesha is traditionally linked to serpent symbolism — penetrating insight, hypnotic charm, and hidden knowledge. Those connected to it are often described as perceptive, strategic, and difficult to deceive." },
  { slug: "magha", name: "Magha", order: 10, deity: "The Pitrs, ancestral spirits", rulingPlanet: "Ketu", symbol: "Royal throne", description: "Magha means 'the mighty one' and is traditionally connected to ancestry, authority, and legacy. It is associated with a natural dignity and a strong pull toward honoring tradition and family lineage." },
  { slug: "purva-phalguni", name: "Purva Phalguni", order: 11, deity: "Bhaga, god of good fortune and pleasure", rulingPlanet: "Venus", symbol: "Front legs of a bed, hammock", description: "Purva Phalguni is traditionally associated with pleasure, creativity, and romance. Those connected to it are often described as warm, sociable, and gifted at putting others at ease." },
  { slug: "uttara-phalguni", name: "Uttara Phalguni", order: 12, deity: "Aryaman, god of patronage and contracts", rulingPlanet: "Sun", symbol: "Back legs of a bed", description: "Uttara Phalguni is linked in tradition to partnership, generosity, and helpfulness. It is associated with reliability, fairness in relationships, and a genuine wish to support others' success." },
  { slug: "hasta", name: "Hasta", order: 13, deity: "Savitar, solar deity of skill", rulingPlanet: "Moon", symbol: "Hand or fist", description: "Hasta means 'hand' and is traditionally tied to skill, craftsmanship, and cleverness. Those connected to it are often described as dexterous problem-solvers who are good with their hands and quick-witted in negotiation." },
  { slug: "chitra", name: "Chitra", order: 14, deity: "Tvashtar / Vishvakarma, celestial architect", rulingPlanet: "Mars", symbol: "Bright jewel or pearl", description: "Chitra means 'the brilliant one' and is traditionally connected to craftsmanship, design, and personal magnetism. It is associated with a strong aesthetic sense and a talent for building or creating striking things." },
  { slug: "swati", name: "Swati", order: 15, deity: "Vayu, god of wind", rulingPlanet: "Rahu", symbol: "Young shoot blown by wind", description: "Swati is traditionally associated with independence and flexibility, much like wind — able to move freely and adapt to circumstances. Those connected to it are often described as diplomatic, self-reliant, and quietly resilient." },
  { slug: "vishakha", name: "Vishakha", order: 16, deity: "Indra and Agni, twin deities of purpose and fire", rulingPlanet: "Jupiter", symbol: "Triumphal archway", description: "Vishakha is traditionally connected to determination and goal-driven achievement — the symbolic archway representing a clear path toward victory. It is associated with focus, ambition, and single-minded purpose." },
  { slug: "anuradha", name: "Anuradha", order: 17, deity: "Mitra, god of friendship and alliance", rulingPlanet: "Saturn", symbol: "Lotus flower, archway", description: "Anuradha is traditionally linked to friendship, loyalty, and successful collaboration. Those connected to it are often described as devoted, well-organized, and skilled at building lasting alliances." },
  { slug: "jyeshtha", name: "Jyeshtha", order: 18, deity: "Indra, king of the gods", rulingPlanet: "Mercury", symbol: "Circular amulet, umbrella", description: "Jyeshtha means 'the eldest' and is traditionally tied to seniority, protection, and courageous responsibility. It is associated with natural authority and a protective instinct toward those who depend on you." },
  { slug: "mula", name: "Mula", order: 19, deity: "Nirriti, goddess of destruction and dissolution", rulingPlanet: "Ketu", symbol: "Bundle of roots", description: "Mula means 'the root' and is traditionally associated with getting to the very foundation of things, often through uprooting what no longer serves. It is linked to investigation, spiritual searching, and radical honesty." },
  { slug: "purva-ashadha", name: "Purva Ashadha", order: 20, deity: "Apas, the water deity", rulingPlanet: "Venus", symbol: "Fan or winnowing basket", description: "Purva Ashadha means 'the early invincible one' and is traditionally tied to early, unstoppable momentum. It is associated with persuasive confidence and pride in one's own convictions." },
  { slug: "uttara-ashadha", name: "Uttara Ashadha", order: 21, deity: "The Vishvadevas, universal gods", rulingPlanet: "Sun", symbol: "Elephant tusk", description: "Uttara Ashadha means 'the later invincible one' and is traditionally connected to lasting, hard-won victory. Those linked to it are often described as principled, patient, and ultimately unstoppable once committed to a goal." },
  { slug: "shravana", name: "Shravana", order: 22, deity: "Vishnu, the preserver", rulingPlanet: "Moon", symbol: "Ear, or three footprints", description: "Shravana means 'to hear' and is traditionally associated with listening, learning, and the transmission of wisdom. It is linked to strong communication skills and a genuine gift for absorbing and sharing knowledge." },
  { slug: "dhanishta", name: "Dhanishta", order: 23, deity: "The Vasus, gods of material abundance", rulingPlanet: "Mars", symbol: "Drum or flute", description: "Dhanishta is traditionally tied to music, rhythm, and prosperity. Those connected to it are often described as energetic, generous, and gifted in the arts or in group leadership." },
  { slug: "shatabhisha", name: "Shatabhisha", order: 24, deity: "Varuna, god of cosmic law and the seas", rulingPlanet: "Rahu", symbol: "Empty circle, hundred stars/healers", description: "Shatabhisha means 'a hundred healers' and is traditionally connected to healing, secrecy, and independent thought. It is associated with strong intuition and a preference for solitude while working toward truth." },
  { slug: "purva-bhadrapada", name: "Purva Bhadrapada", order: 25, deity: "Aja Ekapada, one-footed serpent deity", rulingPlanet: "Jupiter", symbol: "Front legs of a funeral cot, sword", description: "Purva Bhadrapada is traditionally linked to intensity, transformation, and spiritual fire, sometimes carrying an ascetic or fierce edge. It is associated with passionate conviction and a willingness to burn away illusion." },
  { slug: "uttara-bhadrapada", name: "Uttara Bhadrapada", order: 26, deity: "Ahir Budhnya, serpent of the deep", rulingPlanet: "Saturn", symbol: "Back legs of a funeral cot, twin serpents", description: "Uttara Bhadrapada is traditionally associated with deep wisdom, patience, and quiet inner strength drawn from stillness. Those connected to it are often described as steady, compassionate, and unusually tolerant of hardship." },
  { slug: "revati", name: "Revati", order: 27, deity: "Pushan, nourisher and protector of travelers", rulingPlanet: "Mercury", symbol: "Fish, or a drum", description: "Revati is the final Nakshatra and is traditionally tied to safe journeys, nourishment, and gentle completion. It is associated with compassion, guidance for others, and a graceful sense of closure at the end of a cycle." },
];

export function getNakshatraBySlug(slug: string): NakshatraInfo | undefined {
  return NAKSHATRAS.find((n) => n.slug === slug);
}
