const fs = require('fs');
const path = require('path');

const en = {
  "privacy.title": "Privacy Policy",
  "privacy.last_updated": "Last updated: {date}",
  "privacy.s1.title": "The short version",
  "privacy.s1.p1": "Cosmic Numbers has no backend, no user accounts, and no database. The name and date of birth you type in are used only to calculate your numerology, horoscope, or compatibility results directly in your own browser — that data is never sent to us or stored on any server we control.",
  "privacy.s2.title": "What information we process",
  "privacy.s2.p1": "When you use a calculator (Numerology, Horoscope, Compatibility, or Nakshatra), the name and date of birth you enter are processed entirely client-side, in JavaScript running on your device, to compute your result. We do not transmit this information to a server, and we do not collect, log, or store it anywhere.",
  "privacy.s2.p2": "If you use a \"Share\" link for a result, that information (e.g. your name and life path number) is encoded directly into the URL as query parameters so the page can regenerate the same result for whoever opens the link. It is not saved in a database — it exists only in that URL.",
  "privacy.s3.title": "Local storage & gamification",
  "privacy.s3.p1": "To power streaks, XP, and badges, Cosmic Numbers stores small pieces of data (such as your current streak count and which badges you've unlocked) in your browser's local storage. This data stays on your device, is never transmitted to us, and can be cleared at any time by clearing your browser's site data for this domain.",
  "privacy.s4.title": "Hosting & server logs",
  "privacy.s4.p1": "This site is hosted on Vercel. Like virtually any web host, Vercel's infrastructure may automatically record standard technical request logs (such as IP address, browser type, and request timestamps) for security, performance, and abuse-prevention purposes. We do not access these logs to identify individuals, and they are not linked to the numerology or horoscope data you enter.",
  "privacy.s5.title": "Advertising & Google AdSense",
  "privacy.s5.p1": "Cosmic Numbers may display advertisements served by Google AdSense to support the free tools on this site. If ads are enabled, Google and its partners may use cookies, device identifiers, and similar technologies to serve ads based on your prior visits to this and other websites, and to measure ad performance.",
  "privacy.s5.p2": "You can learn more about how Google uses data when you use its partners' sites or apps, and opt out of personalized advertising, at ",
  "privacy.s5.p3": ". You can also manage your ad personalization settings directly at ",
  "privacy.s5.p4": ". Cosmic Numbers itself does not control how Google's ad systems process your data — that is governed by Google's own privacy policy.",
  "privacy.s6.title": "Children's privacy",
  "privacy.s6.p1": "This site is intended for a general audience and does not knowingly collect personal information from children. Since no personal data is stored on our servers to begin with, there is no account or profile data to request the deletion of.",
  "privacy.s7.title": "Changes to this policy",
  "privacy.s7.p1": "We may update this Privacy Policy from time to time, for example if we enable new features or advertising services. Any changes will be reflected on this page with an updated \"last updated\" date.",

  "terms.title": "Terms of Service",
  "terms.s1.title": "Entertainment purposes only",
  "terms.s1.p1": "Cosmic Numbers provides numerology readings, daily horoscopes, zodiac compatibility scores, and nakshatra information for entertainment and self-reflection purposes only. Numerology and astrology are traditional and spiritual systems of interpretation, not scientific fact, and nothing on this site constitutes medical, legal, financial, psychological, or professional advice of any kind.",
  "terms.s1.p2": "You should not make important life decisions — financial, medical, relationship, or otherwise — based solely on content from this site.",
  "terms.s2.title": "No account, free to use",
  "terms.s2.p1": "Cosmic Numbers does not require an account or payment to use. Streaks, XP, and badges shown on the site are a lightweight gamification layer stored only in your browser, and have no monetary value.",
  "terms.s3.title": "Provided \"as is\"",
  "terms.s3.p1": "This site and all of its content are provided \"as is\" and \"as available,\" without warranties of any kind, whether express or implied, including but not limited to accuracy, reliability, availability, or fitness for a particular purpose. We do not guarantee the site will be uninterrupted, error-free, or available at all times.",
  "terms.s4.title": "Limitation of liability",
  "terms.s4.p1": "To the fullest extent permitted by law, Cosmic Numbers and its creators are not liable for any damages or losses arising from your use of, or reliance on, this site or its content, including any decisions made based on a numerology reading, horoscope, or compatibility result.",
  "terms.s5.title": "Acceptable use",
  "terms.s5.p1": "You agree not to misuse the site — for example, by attempting to disrupt its normal operation, scraping it at abusive volume, or using it to harass or impersonate others via the shareable result links.",
  "terms.s6.title": "Third-party advertising",
  "terms.s6.p1": "This site may display advertising served by Google AdSense or similar ad networks. Ads are subject to the ad network's own terms and privacy practices, described further in our ",
  "terms.s7.title": "Changes to these terms",
  "terms.s7.p1": "We may update these Terms of Service from time to time as the site evolves. Continued use of the site after changes are posted means you accept the updated terms. We'll update the \"last updated\" date above whenever changes are made."
};

const hi = {
  "privacy.title": "गोपनीयता नीति (Privacy Policy)",
  "privacy.last_updated": "अंतिम अपडेट: {date}",
  "privacy.s1.title": "संक्षिप्त विवरण",
  "privacy.s1.p1": "Cosmic Numbers का कोई बैकएंड, कोई उपयोगकर्ता खाता और कोई डेटाबेस नहीं है। आपके द्वारा टाइप किया गया नाम और जन्मतिथि केवल आपके अपने ब्राउज़र में सीधे आपके अंक ज्योतिष, राशिफल या संगतता परिणामों की गणना करने के लिए उपयोग किया जाता है — वह डेटा कभी भी हमें नहीं भेजा जाता है या हमारे द्वारा नियंत्रित किसी भी सर्वर पर संग्रहीत नहीं किया जाता है।",
  "privacy.s2.title": "हम कौन सी जानकारी प्रोसेस करते हैं",
  "privacy.s2.p1": "जब आप कैलकुलेटर का उपयोग करते हैं, तो आपके द्वारा दर्ज किया गया नाम और जन्मतिथि पूरी तरह से क्लाइंट-साइड संसाधित होती है। हम इस जानकारी को सर्वर पर संचारित नहीं करते हैं, और हम इसे कहीं भी एकत्र, लॉग या संग्रहीत नहीं करते हैं।",
  "privacy.s2.p2": "यदि आप किसी परिणाम के लिए 'शेयर' लिंक का उपयोग करते हैं, तो वह जानकारी सीधे URL में एन्कोड हो जाती है। इसे डेटाबेस में सहेजा नहीं जाता है — यह केवल उस URL में मौजूद है।",
  "privacy.s3.title": "स्थानीय संग्रहण और गेमिफिकेशन",
  "privacy.s3.p1": "स्ट्रीक्स, XP और बैज को पावर देने के लिए, Cosmic Numbers आपके ब्राउज़र के स्थानीय संग्रहण में डेटा के छोटे टुकड़े संग्रहीत करता है। यह डेटा आपके डिवाइस पर रहता है और कभी भी हमें नहीं भेजा जाता है।",
  "privacy.s4.title": "होस्टिंग और सर्वर लॉग",
  "privacy.s4.p1": "यह साइट Vercel पर होस्ट की गई है। Vercel का बुनियादी ढांचा सुरक्षा उद्देश्यों के लिए स्वचालित रूप से मानक तकनीकी अनुरोध लॉग (जैसे IP पता) रिकॉर्ड कर सकता है।",
  "privacy.s5.title": "विज्ञापन और Google AdSense",
  "privacy.s5.p1": "Cosmic Numbers इस साइट पर मुफ़्त टूल का समर्थन करने के लिए Google AdSense द्वारा विज्ञापनों को प्रदर्शित कर सकता है।",
  "privacy.s5.p2": "आप इसके बारे में अधिक जान सकते हैं कि Google डेटा का उपयोग कैसे करता है, यहाँ: ",
  "privacy.s5.p3": "। आप अपनी विज्ञापन वैयक्तिकरण सेटिंग भी सीधे यहाँ प्रबंधित कर सकते हैं: ",
  "privacy.s5.p4": "।",
  "privacy.s6.title": "बच्चों की गोपनीयता",
  "privacy.s6.p1": "यह साइट सामान्य दर्शकों के लिए है और जानबूझकर बच्चों से व्यक्तिगत जानकारी एकत्र नहीं करती है।",
  "privacy.s7.title": "इस नीति में परिवर्तन",
  "privacy.s7.p1": "हम समय-समय पर इस गोपनीयता नीति को अपडेट कर सकते हैं।",
  "terms.title": "सेवा की शर्तें (Terms of Service)",
  "terms.s1.title": "केवल मनोरंजन के उद्देश्य से",
  "terms.s1.p1": "Cosmic Numbers केवल मनोरंजन और आत्म-चिंतन के उद्देश्यों के लिए अंक ज्योतिष, दैनिक राशिफल और नक्षत्र जानकारी प्रदान करता है।",
  "terms.s1.p2": "आपको इस साइट की सामग्री के आधार पर जीवन के महत्वपूर्ण निर्णय नहीं लेने चाहिए।",
  "terms.s2.title": "कोई खाता नहीं, उपयोग करने के लिए मुफ़्त",
  "terms.s2.p1": "Cosmic Numbers का उपयोग करने के लिए किसी खाते या भुगतान की आवश्यकता नहीं है।",
  "terms.s3.title": "\"जैसी है\" प्रदान की गई",
  "terms.s3.p1": "यह साइट और इसकी सभी सामग्री \"जैसी है\" प्रदान की जाती है, बिना किसी प्रकार की वारंटी के।",
  "terms.s4.title": "दायित्व की सीमा",
  "terms.s4.p1": "Cosmic Numbers और इसके निर्माता इस साइट के उपयोग से होने वाले किसी भी नुकसान के लिए उत्तरदायी नहीं हैं।",
  "terms.s5.title": "स्वीकार्य उपयोग",
  "terms.s5.p1": "आप साइट का दुरुपयोग न करने के लिए सहमत हैं, जैसे इसे खुरचना या स्पैम करना।",
  "terms.s6.title": "तृतीय-पक्ष विज्ञापन",
  "terms.s6.p1": "यह साइट विज्ञापन प्रदर्शित कर सकती है। विज्ञापन नेटवर्क की अपनी शर्तों के अधीन हैं, जो हमारी में वर्णित हैं ",
  "terms.s7.title": "इन शर्तों में परिवर्तन",
  "terms.s7.p1": "हम समय-समय पर इन सेवा की शर्तों को अपडेट कर सकते हैं।"
};

const de = {
  "privacy.title": "Datenschutzrichtlinie",
  "privacy.last_updated": "Zuletzt aktualisiert: {date}",
  "privacy.s1.title": "Die Kurzfassung",
  "privacy.s1.p1": "Cosmic Numbers hat kein Backend, keine Benutzerkonten und keine Datenbank. Der Name und das Geburtsdatum, die Sie eingeben, werden nur verwendet, um Ihre Ergebnisse direkt in Ihrem eigenen Browser zu berechnen — diese Daten werden niemals an uns gesendet oder gespeichert.",
  "privacy.s2.title": "Welche Informationen wir verarbeiten",
  "privacy.s2.p1": "Wenn Sie einen Taschenrechner verwenden, werden der Name und das Geburtsdatum vollständig clientseitig in JavaScript verarbeitet. Wir übertragen diese Informationen nicht an einen Server.",
  "privacy.s2.p2": "Wenn Sie einen \"Teilen\"-Link verwenden, werden diese Informationen direkt in die URL als Abfrageparameter codiert. Sie werden nicht in einer Datenbank gespeichert.",
  "privacy.s3.title": "Lokale Speicherung & Gamification",
  "privacy.s3.p1": "Um Streaks, XP und Badges zu betreiben, speichert Cosmic Numbers kleine Datenmengen im lokalen Speicher Ihres Browsers. Diese Daten bleiben auf Ihrem Gerät.",
  "privacy.s4.title": "Hosting & Server-Protokolle",
  "privacy.s4.p1": "Diese Seite wird auf Vercel gehostet. Vercels Infrastruktur kann automatisch Standardprotokolle (wie IP-Adresse) zu Sicherheitszwecken aufzeichnen.",
  "privacy.s5.title": "Werbung & Google AdSense",
  "privacy.s5.p1": "Cosmic Numbers kann von Google AdSense bereitgestellte Werbung anzeigen, um die kostenlosen Tools zu unterstützen.",
  "privacy.s5.p2": "Sie können mehr darüber erfahren, wie Google Daten verwendet, und die personalisierte Werbung deaktivieren unter ",
  "privacy.s5.p3": ". Sie können Ihre Einstellungen auch verwalten unter ",
  "privacy.s5.p4": ".",
  "privacy.s6.title": "Datenschutz von Kindern",
  "privacy.s6.p1": "Diese Seite richtet sich an ein allgemeines Publikum und sammelt nicht wissentlich persönliche Daten von Kindern.",
  "privacy.s7.title": "Änderungen an dieser Richtlinie",
  "privacy.s7.p1": "Wir können diese Datenschutzrichtlinie von Zeit zu Zeit aktualisieren.",
  "terms.title": "Nutzungsbedingungen",
  "terms.s1.title": "Nur zu Unterhaltungszwecken",
  "terms.s1.p1": "Cosmic Numbers bietet Numerologie und Horoskope nur zu Unterhaltungs- und Selbstreflexionszwecken an.",
  "terms.s1.p2": "Sie sollten keine wichtigen Lebensentscheidungen ausschließlich aufgrund von Inhalten dieser Seite treffen.",
  "terms.s2.title": "Kein Konto, kostenlos",
  "terms.s2.p1": "Cosmic Numbers erfordert kein Konto oder Zahlung. Streaks und XP haben keinen monetären Wert.",
  "terms.s3.title": "Bereitgestellt \"wie gesehen\"",
  "terms.s3.p1": "Diese Seite wird \"wie besehen\" und \"wie verfügbar\" ohne Garantien jeglicher Art bereitgestellt.",
  "terms.s4.title": "Haftungsbeschränkung",
  "terms.s4.p1": "Cosmic Numbers und seine Schöpfer haften nicht für Schäden, die aus Ihrer Nutzung dieser Seite entstehen.",
  "terms.s5.title": "Zulässige Nutzung",
  "terms.s5.p1": "Sie stimmen zu, die Seite nicht zu missbrauchen (z. B. durch Scraping oder Spamming).",
  "terms.s6.title": "Werbung von Dritten",
  "terms.s6.p1": "Diese Seite kann Werbung anzeigen, die in unserer beschrieben sind ",
  "terms.s7.title": "Änderungen an diesen Bedingungen",
  "terms.s7.p1": "Wir können diese Nutzungsbedingungen von Zeit zu Zeit aktualisieren."
};

const zh = {
  "privacy.title": "隐私政策",
  "privacy.last_updated": "最后更新: {date}",
  "privacy.s1.title": "简短版本",
  "privacy.s1.p1": "Cosmic Numbers 没有后端、没有用户帐户也没有数据库。您输入的姓名和出生日期仅用于直接在您自己的浏览器中计算您的结果——该数据永远不会发送给我们或存储在我们的服务器上。",
  "privacy.s2.title": "我们处理什么信息",
  "privacy.s2.p1": "当您使用计算器时，您输入的姓名和出生日期将完全在客户端处理。我们不向服务器传输此信息。",
  "privacy.s2.p2": "如果您使用“分享”链接，该信息将直接编码到 URL 中，而不是保存在数据库中。",
  "privacy.s3.title": "本地存储与游戏化",
  "privacy.s3.p1": "为了驱动连续记录、XP 和徽章，Cosmic Numbers 在您浏览器的本地存储中保存小块数据。这些数据保留在您的设备上。",
  "privacy.s4.title": "托管和服务器日志",
  "privacy.s4.p1": "本网站托管在 Vercel 上。为了安全目的，Vercel 的基础设施可能会自动记录标准技术请求日志（如 IP 地址）。",
  "privacy.s5.title": "广告和 Google AdSense",
  "privacy.s5.p1": "Cosmic Numbers 可能会显示由 Google AdSense 提供的广告以支持免费工具。",
  "privacy.s5.p2": "您可以了解 Google 如何使用数据并在以下位置选择退出个性化广告 ",
  "privacy.s5.p3": "。您也可以直接在以下位置管理设置 ",
  "privacy.s5.p4": "。",
  "privacy.s6.title": "儿童隐私",
  "privacy.s6.p1": "本网站面向普通受众，不会故意收集儿童的个人信息。",
  "privacy.s7.title": "本政策的变更",
  "privacy.s7.p1": "我们可能会不时更新本隐私政策。",
  "terms.title": "服务条款",
  "terms.s1.title": "仅供娱乐",
  "terms.s1.p1": "Cosmic Numbers 提供的命理学和星座内容仅供娱乐和自我反省之用。",
  "terms.s1.p2": "您不应仅根据本网站的内容做出重要的人生决定。",
  "terms.s2.title": "无需帐户，免费使用",
  "terms.s2.p1": "使用 Cosmic Numbers 不需要帐户或付款。连续记录和 XP 没有货币价值。",
  "terms.s3.title": "“按原样”提供",
  "terms.s3.p1": "本网站“按原样”提供，没有任何形式的保证。",
  "terms.s4.title": "责任限制",
  "terms.s4.p1": "Cosmic Numbers 及其创建者对您使用本网站而产生的任何损害不承担责任。",
  "terms.s5.title": "可接受的使用",
  "terms.s5.p1": "您同意不滥用本网站（例如抓取或发送垃圾邮件）。",
  "terms.s6.title": "第三方广告",
  "terms.s6.p1": "本网站可能会显示广告。广告受我们的进一步描述 ",
  "terms.s7.title": "这些条款的变更",
  "terms.s7.p1": "我们可能会不时更新这些服务条款。"
};

const gu = {
  "privacy.title": "ગોપનીયતા નીતિ",
  "privacy.last_updated": "છેલ્લે અપડેટ: {date}",
  "privacy.s1.title": "ટૂંકી આવૃત્તિ",
  "privacy.s1.p1": "Cosmic Numbers પાસે કોઈ બેકએન્ડ, કોઈ વપરાશકર્તા ખાતું અને કોઈ ડેટાબેઝ નથી. તમારું ડેટા સીધું તમારા બ્રાઉઝરમાં ગણતરી માટે વપરાય છે — તે ક્યારેય સર્વર પર સંગ્રહિત થતું નથી.",
  "privacy.s2.title": "અમે કઈ માહિતી પર પ્રક્રિયા કરીએ છીએ",
  "privacy.s2.p1": "નામ અને જન્મ તારીખ સંપૂર્ણપણે ક્લાયંટ-સાઇડ પર પ્રક્રિયા કરવામાં આવે છે. અમે આ માહિતી સર્વર પર મોકલતા નથી.",
  "privacy.s2.p2": "જો તમે 'શેર' લિંકનો ઉપયોગ કરો છો, તો માહિતી URL માં એન્કોડ થાય છે, ડેટાબેઝમાં સાચવવામાં આવતી નથી.",
  "privacy.s3.title": "સ્થાનિક સંગ્રહ અને ગેમિફિકેશન",
  "privacy.s3.p1": "સ્ટ્રીક્સ અને XP માટે, Cosmic Numbers તમારા બ્રાઉઝરના સ્થાનિક સંગ્રહમાં ડેટા સાચવે છે.",
  "privacy.s4.title": "હોસ્ટિંગ અને સર્વર લૉગ્સ",
  "privacy.s4.p1": "આ સાઇટ Vercel પર હોસ્ટ થયેલ છે. સુરક્ષા હેતુઓ માટે તે પ્રમાણભૂત લૉગ્સ રેકોર્ડ કરી શકે છે.",
  "privacy.s5.title": "જાહેરાત અને Google AdSense",
  "privacy.s5.p1": "Cosmic Numbers મફત સાધનોને ટેકો આપવા માટે Google AdSense ની જાહેરાતો બતાવી શકે છે.",
  "privacy.s5.p2": "Google ડેટાનો ઉપયોગ કેવી રીતે કરે છે તે જાણો: ",
  "privacy.s5.p3": ". તમે સેટિંગ્સ સંચાલિત કરી શકો છો: ",
  "privacy.s5.p4": ".",
  "privacy.s6.title": "બાળકોની ગોપનીયતા",
  "privacy.s6.p1": "આ સાઇટ સામાન્ય પ્રેક્ષકો માટે છે અને બાળકો પાસેથી વ્યક્તિગત માહિતી એકત્રિત કરતી નથી.",
  "privacy.s7.title": "આ નીતિમાં ફેરફારો",
  "privacy.s7.p1": "અમે સમયાંતરે આ નીતિને અપડેટ કરી શકીએ છીએ.",
  "terms.title": "સેવાની શરતો",
  "terms.s1.title": "માત્ર મનોરંજન માટે",
  "terms.s1.p1": "અંકશાસ્ત્ર અને રાશિફળ માત્ર મનોરંજન અને આત્મ-ચિંતન માટે છે.",
  "terms.s1.p2": "તમારે સાઇટના આધારે મહત્વપૂર્ણ નિર્ણયો લેવા જોઈએ નહીં.",
  "terms.s2.title": "કોઈ ખાતું નથી, વાપરવા માટે મફત",
  "terms.s2.p1": "કોઈ ચુકવણીની જરૂર નથી. XP અને બેજનું કોઈ નાણાકીય મૂલ્ય નથી.",
  "terms.s3.title": "\"જેમ છે તેમ\" પ્રદાન કરેલ",
  "terms.s3.p1": "આ સાઇટ કોઈ પણ પ્રકારની વોરંટી વિના પૂરી પાડવામાં આવે છે.",
  "terms.s4.title": "જવાબદારીની મર્યાદા",
  "terms.s4.p1": "Cosmic Numbers કોઈપણ નુકસાન માટે જવાબદાર નથી.",
  "terms.s5.title": "સ્વીકાર્ય ઉપયોગ",
  "terms.s5.p1": "તમે સાઇટનો દુરુપયોગ ન કરવા માટે સંમત છો.",
  "terms.s6.title": "તૃતીય-પક્ષ જાહેરાત",
  "terms.s6.p1": "આ સાઇટ જાહેરાતો બતાવી શકે છે જે અમારી માં વર્ણવેલ છે ",
  "terms.s7.title": "આ શરતોમાં ફેરફારો",
  "terms.s7.p1": "અમે સમયાંતરે આ શરતોને અપડેટ કરી શકીએ છીએ."
};

const locales = { en, hi, de, zh, gu };

for (const [lang, dict] of Object.entries(locales)) {
  const filePath = path.join(__dirname, `src/locales/${lang}.json`);
  let content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  content = { ...content, ...dict };
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
}

console.log("Translations injected.");
